site_name: !ENV [DOCS_SITE_NAME, 'Ryubing Docs']
site_url: !ENV [DOCS_SITE_URL, 'https://docs.ryujinx.app']
repo_url: "https://git.ryujinx.app/ryubing/ryujinx"
repo_name: ""
edit_uri: ""
theme:
  name: material
  logo: favicon.png
  favicon: favicon.png
  features:
    - header.autohide
    - navigation.expand
    - navigation.instant
  palette:
    - scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode


nav:
  - Home: index.md
  - Guides:
    - "Multiplayer (LDN/Local Wireless) Guide": guides/ldn-guide.md
    - "Setup & Configuration Guide": guides/setup-guide.md
    - Dumping:
      - "Firmware Dump Guide": guides/dumping/fw.md
      - "Games, Updates, and DLC Dump Guide": guides/dumping/game-content.md
      - "Key Dump Guide": guides/dumping/keys.md
      - "How to setup USB dumping": guides/dumping/usb-dumping.md
  - Information:
    - "What is dumping?": info/dumping.md
    - Changelog: info/changelog.md
    - "FAQ & Troubleshooting": "info/faq-&-troubleshooting.md"
  - Developers:
    - "Contributing to the Project": dev/contributing.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ryujinx
      name: Discord Server
      social:
    - icon: fontawesome/solid/house
      link: https://ryujinx.app
      name: Main Website